### ISSUE TITLE
Donation address?

### ISSUE THREAD

**Issue by mtlynch** [travis-r6s/gridsome-starter-shopify#14]
Thanks for making this starter, @thetre97! I'm using it on [TinyPilot's website](https://tinypilotkvm.com/). Before your plugin, I was just using the Shopify buy button, so people could only order one item at a time. This starter has increased my revenues, so I'd like to contribute back.

Do you accept donations? Perhaps via a paypal.me URL? You can place a file at `.github/FUNDING.yml` that lets people know how to contribute donations ([example](https://github.com/mtlynch/tinypilot/blob/c2aed0cc2a4569614e9758d53a0632d4f8963e3d/.github/FUNDING.yml)).

**Comment by travis-r6s** [comment]
Thank you for the hint, and the support - appreciate it! 😊
I have just added my paypal.me link.

**Comment by mtlynch** [comment]
Thanks!
