### ISSUE TITLE
Cannot query field "images" on type "ShopifyProduct". Did you mean "tags" error

### ISSUE THREAD

**Issue by cweachock** [travis-r6s/gridsome-starter-shopify#16]
Hi there, 

Im new to gridsome and using graphql, trying to set up your boilerplate but I seem to getting errors when I run `gridsome develop` 
from the terminal in vscode **after** I created the .env file and added my shopify store credentials (store name and storefront api token)

Error: Cannot query field "images" on type "ShopifyProduct". Did you mean "tags"?
Error: Cannot query field "images" on type "ShopifyProduct". Did you mean "tags"?
Error: Cannot query field "image" on type "ShopifyCollection".

from: Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js): 

any thoughts?

**Comment by travis-r6s** [comment]
@cweachock Please ensure that you have images added to a product and a collection, or remove the image query field from the page queries.

If there are no images in either of those, then the data from Shopify will be null, so those fields won't be added to the Gridsome schema - hence it cannot find the field.

**Comment by cweachock** [comment]
Thanks @thetre97 ! Ah that makes sense. Thank you for answering so quickly. 

I actually ended up getting the official Gridsome graphQL plugin to work for right now: https://gridsome.org/plugins/@gridsome/source-graphql was playing with that a little bit. :)
