### ISSUE TITLE
Refetching Store Data?

### ISSUE THREAD

**Issue by theworkerant** [travis-r6s/gridsome-starter-shopify#6]
I assume based on the README you'll need to rebuild your site to fetch any changes made to your store? Is there a proposed workflow for this? Do it manually??

**Comment by travis-r6s** [comment]
That is correct - in development, that is done easily enough by just restarting the Dev server. In production, you can use Shopify notifications to rebuild the site when content changes.

So for example if you were using Netlify to host your gridsome site, you can get the build webhook from your account, and add it to a Shopify "product changed" notification - that webhook will then get pinged everytime you add/update a product, and the site will in turn get rebuilt to pull in the new changes. This can be replicated for collections etc.

Does that help?

**Comment by theworkerant** [comment]
Yes thank you kindly!
